[package]
name = "rd-video-codec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
thiserror = "1.0.38"

mfx-dispatch-sys = { path = "../mfx-dispatch-sys" }